# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!

target 'BCTeam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCTeam
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'IQKeyboardManager'
  pod 'TZImagePickerController'#相册图片多选
  pod 'DZNEmptyDataSet'
  pod 'AliyunOSSiOS'
  pod 'Bugly'
  pod 'FDFullscreenPopGesture'
  pod 'Masonry'
  pod 'YYCategories'
  pod 'DateTools'

end
